version: '3.1'

services:
  mariadb:
    image: mariadb:10.5
    container_name: mariadb-compose
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
    - ./todo.sql:/docker-entrypoint-initdb.d/sql-db.sql