name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Install dependencies
      run: mvn install -DskipTests

    - name: Run linter
      run: |
        mvn checkstyle:check || echo "Checkstyle errors ignored."

    - name: Run tests
      run: mvn test

    - name: Check test results
      run: |
        TEST_RESULTS=$(mvn surefire-report:report-only)
        if [[ $TEST_RESULTS != *"Tests run: 100, Failures: 0, Errors: 0, Skipped: 0"* ]]; then
          echo "Tests did not meet the required pass rate."
          exit 1
        fi

    - name: Deploy to staging
      if: success()
      run: |
        echo "Deploying to staging environment..."
        # Add your deployment script/command here

    - name: Publish test results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/surefire-reports

    - name: Use GitHub Secrets
      run: |
        echo "Using GitHub Secrets..."
        # Example: export API_KEY=${{ secrets.API_KEY }}

    - name: Handle errors
      if: failure()
      run: |
        echo "Build or tests failed. Please check the logs for details."
